version: "3"
services:
  ubuntu-texlive-ja:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ../:/workdir
      - ./.latexmkrc:/root/.latexmkrc
      - ~/.gitconfig:/root/.gitconfig
    environment:
      SHELL: "/bin/bash"
